services:
  - type: web
    name: exur-atmospheric-intelligence
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: NASA_FIRMS_KEY
        sync: false
      - key: OPENAQ_API_KEY
        sync: false
      - key: NEXT_PUBLIC_CARTO_KEY
        sync: false
